#!/usr/bin/env bash

source "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/lib/configure.sh"
source "$CSCRIPT_LIB/batlib.sh"
plaintext=false

run_paths=()

batman_banner() {
    cat "$CSCRIPT_LIB/batman_banner.txt"
    echo ""
    echo ""
}

# This is not a very good attempt at confirming that the file in question
# contains the minimum number of function calls that all tests suites 
# should have.
# TODO: Revisit this.
valid_test_file() {
    local path="$@"
    local status=0
    grep -qE "run_test .* .*" "$path"; status=$((status + $?))
    grep -qE "case_pass$" "$path"; status=$((status + $?))

    return $status
}

run_tests() {
    for encoded_path in "${run_paths[@]}"; do
        pushd . &>/dev/null
        [[ ! "$encoded_path" == *"_test.sh" ]] && continue

        local path="${encoded_path/$CSCRIPT_SPACE_ENCODE/\ }"

        if ! valid_test_file "$path"; then continue; fi

        start_suite "$path"
        . "$path"
        end_suite
        popd &>/dev/null
    done
}

while getopts "p" opt; do
    case $opt in
        p)
            plaintext=true
            ;;
        *)  ;;
    esac
done
shift $(($OPTIND - 1))

for p in "$@"; do
    run_paths+=("${p// /$CSCRIPT_SPACE_ENCODE}")
done

batman_banner

if $plaintext; then
    run_tests | unfancy
    bat_summary | unfancy
else
    run_tests
    bat_summary
fi


exit $BAT_STATUS