#!/usr/bin/env bash

source "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/lib/configure.sh"
source "$CSCRIPT_LIB/batlib.sh"

plaintext=false

while getopts "p" opt; do
    case $opt in
        p)
            plaintext=true
            ;;
        *)  ;;
    esac
done
shift $(($OPTIND - 1))

for p in "$@"; do
    RUN_PATHS+=("${p// /$CSCRIPT_SPACE_ENCODE}")
done

bat_banner

if $plaintext; then
    bat_run_tests | unfancy
    bat_summary | unfancy
else
    bat_run_tests
    bat_summary
fi


exit $BAT_STATUS