#!/usr/bin/env bash

source "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/lib/configure.sh"

__CPACK_PATH="$(basename $0)"
__CPACK_CMDS=("extract" "compress" "help")
__CPACK_TYPES=("7z" "zip" "gzip" "bzip" "tar" "tgz" "xz" "wim" "rar")

#TODO: Add support for: RAR and ISO
declare -A __CPACK_CMD_DEF=(
    ["7z_extract"]="7z;_;7z x -y FILE"
    ["7z_compress"]="7z;_;7z a -y FILE.7z FILE"
    ["zip_extract"]="7z;_;7z x -tzip -y FILE"
    ["zip_compress"]="7z;_;7z a -tzip -y FILE.zip FILE"
    ["bzip_extract"]="bzip2;_;7z x -tbzip2 -y FILE"
    ["bzip_compress"]="bzip2;_;7z a -tbzip2 -y FILE.bz2 FILE"
    ["gzip_extract"]="gzip;_;7z x -tgzip -y FILE"
    ["gzip_compress"]="gzip;_;7z a -tgzip -y FILE.gz FILE"
    ["tar_extract"]="tar;_;7z x -ttar -y FILE"
    ["tar_compress"]="tar;_;7z a -ttar -y FILE.tar FILE"
    ["tgz_extract"]="tar;7z;tar zxf FILE"
    ["tgz_compress"]="tar;7z;tar cf - FILE | 7z a -si FILE.tar.gz"
    ["xz_extract"]="7z;_;7z x -txz -y FILE"
    ["xz_compress"]="7z;_;7z a -txz -y FILE.xy FILE"
    ["wim_extract"]="7z;_;7z x -twim -y FILE"
    ["wim_compress"]="7z;_;7z a -twim -y FILE.wim FILE"
    ["rar_extract"]="unrar;_;unrar x -y FILE"
    ["rar_compress"]="rar;_;rar a -y FILE.rar FILE"
)

__cpack_usage() {
    fancy_print -n -s bold -c cyan "Usage: "
    fancy_print -n -s bold "$__CPACK_PATH "
    fancy_print -n -s underline "COMMAND" 
    echo -n " [options] "
    fancy_print -s underline "TARGET"

    echo ""

    fancy_print -s bold -c green "Options: "
    echo -n "    -t "
    fancy_print -s underline "TYPE"
    echo "        Specify compression type"
    echo "    -d " 
    echo -n "        Treat " && fancy_print -n -s underline "TARGET" && echo " as a directory."
    echo "        Use all applicable files within the directory."
    echo "    -h "
    echo "        Print this help message"

    echo ""

    fancy_print -s bold -c green "Commands: "
    for c in "${__CPACK_CMDS[@]}"; do
        echo "    $c"
    done

    echo ""

    fancy_print -s bold -c green "Types: "
    for c in "${__CPACK_TYPES[@]}"; do
        echo "    $c"
    done
}

__cpack_valid_cmd() {
    local arg="$1"
    for c in "${__CPACK_CMDS[@]}"; do
        [[ "$c" == "$arg" ]] && return 0
    done
    return 1
}

__cpack_valid_type() {
    local arg="$1"
    for c in "${__CPACK_TYPES[@]}"; do
        [[ "$c" == "$arg" ]] && return 0
    done
    return 1
}

__cpack_run() {
    local cmd="$1"
    local pack_type=""
    local use_dir=false
    
    if ! __cpack_valid_cmd "$cmd"; then
        fancy_print -s bold -c red "Invalid Command"
        __cpack_usage
        return 1
    elif [[ "$cmd" == "help" ]]; then
        __cpack_usage
        return 0
    fi

    shift

    # Read Options
    local OPTIND d
    while getopts "dt:" opt; do
        case "$opt" in
            d)
                use_dir=true
                ;;
            t)
                pack_type="$OPTARG"
                ;;
       esac 
    done
    shift $(($OPTIND - 1))

    # Pack Check
    if [[ "$pack_type" == "" ]]; then
        fancy_print -s bold -c red "Missing Pack Type"
        __cpack_usage
        return 1
    elif ! __cpack_valid_type "$pack_type"; then
        fancy_print -s bold -c red "Invalid Pack Type"
        __cpack_usage
        return 1
    fi

    # Path Check
    local target_path="$1"
    if [[ "$target_path" == "" ]]; then
        fancy_print -s bold -c red "Missing Target Path"
        __cpack_usage
        return 1
    fi

    # Select file command
    local cmd_def_key="${pack_type}_$cmd"
    local cmd_def="${__CPACK_CMD_DEF[$cmd_def_key]}"
    local def_split=(${cmd_def//;/ })
    local def_cmd_exe1="${def_split[0]}"
    local def_cmd_exe2="${def_split[1]}"
    local def_cmd="${def_split[@]:2}"
    local def_cmd=(${def_cmd//FILE/$target_path})

    if ! command -v "$def_cmd_exe1" &> /dev/null; then
        fancy_print -n -s bold -c red "Missing Program: "
        echo "$def_cmd_exe1"
        return 1
    fi

    if [[ "$def_cmd_exe2" != "_" ]] && ! command -v "$def_cmd_exe2" &> /dev/null; then
        fancy_print -n -s bold -c red "Missing Program: "
        echo "$def_cmd_exe2"
        return 1
    fi

    # Dir Check
    if [ $use_dir = false ]; then
        if [ ! -f "$target_path" ]; then
            fancy_print -s bold -c red "Invalid File"
            return 1
        fi

        fancy_print -n -s bold -c blue "${cmd^}ing" && echo " $target_path"
        eval "${def_cmd[@]}"
    else
        if [ ! -d "$target_path" ]; then
            fancy_print -s bold -c red "Invalid Directory"
            return 1
        fi

        # TODO: Loop through directory. Process all files.
        #       Spawn each file work in background job
        #       Catch output. Say "queuing up" or something like that
    fi

    return 0
}

__cpack_run "$@"