#!/usr/bin/env bash

cscript_path="$HOME/.local/crono-scripts"

if [ -d "$cscript_path" ]; then
    echo "Updating crono-scripts"
    pushd . && cd $cscript_path && git pull && popd
else
    echo "crono-scripts is not installed!"
    echo "To install, run: curl https://github.com/astercrono/crono-scripts/blob/main/cscript-install | bash"
fi