name: Test Scripts
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  Test-Scripts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Tests"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - run: PATH="$PATH:${{ github.workspace }}"; batman test/*
